// components/vue/cb-components-examples/src/App.vue
<template>
  <div id="app">
    <router-view></router-view>
  </div>
</template>

<script>

export default {
  name: 'app',
  components: {

  },
  created() {
    window.Chargebee.init({
      site: "honeycomics-v3-test",
      publishableKey: "test_qoH22RugUvm5IcxoqUD5Svdcu9mX5figf"
    })
  }
}
</script>

// components/angular-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'angular-app';
  constructor() {
    window['Chargebee'].init({
      site: 'honeycomics-v3-test',
      publishableKey: 'test_qoH22RugUvm5IcxoqUD5Svdcu9mX5figf'
    });
  }
}
