// components/react-app/src/components/example4/Example4.js
import React, { Component } from 'react';
import {CardComponent, CardNumber, CardExpiry, CardCVV} from "@chargebee/chargebee-js-react-wrapper";
import './Example4.css'

export default class Example1 extends Component {
  constructor(props) {
    super(props);
    
    // Ref for card component
    this.cardRef = React.createRef()
    
    this.state = {
      token: "",
      intent: null,
      loading: false,
      firstName: "",
      
      // To store validation error messages
      errorMessage: "",
      errors: {},

      // options for card component
      options: {
        // Custom classes - applied on container elements based on field's state
        classes: {
          focus: 'focus',
          invalid: 'invalid',
          empty: 'empty',
          complete: 'complete',
        },

        style: {
          base: {
            color: '#2a2d5b',
            fontWeight: '500',
            fontFamily: 'Raleway,-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica Neue, sans-serif',
            fontSize: '16px',
            fontSmoothing: 'antialiased',

            ':focus': {
              // color: '#424770',
            },

            '::placeholder': {
              color: '#9293AB',
              fontSize: '14px',
            },

            ':focus::placeholder': {
              color: '#666',
            },
          },
          invalid: {
            color: '#e41029',

            ':focus': {
              color: '#e44d5f',
            },
            '::placeholder': {
              color: '#FFCCA5',
            },
          },
        },

        // locale
        locale: 'en',

        // Custom fonts
        fonts: [
          'https://fonts.googleapis.com/css?family=Raleway:300,500,600'
        ]
      },
    }
  }

  componentDidMount() {
    this.createPaymentIntent().then(intent => {
      this.setState({ intent })
    })
  }

  createPaymentIntent = (payload = {}) => {
    return fetch("http://localhost:4000/payment_intent", {
        headers: {
          'Accept': 'application/json',
          'Content-Type': 'application/json'
        }, 
        method: "POST", 
        body: JSON.stringify(payload)
      }).then(response => response.json())
  }

  authorize = (e) => {
    e.preventDefault();
    this.setState({loading: true});
    
    // Call authorize method through card component's ref
    this.cardRef.current.authorizeWith3ds(this.state.intent).then(authorizedIntent => {
      this.setState({intent: authorizedIntent, loading: false, token: authorizedIntent.id, errorMessage: ""});
    }).catch((error) => {
      console.error(error);
      this.setState({loading: false, token: "", errorMessage: "Problem while authorizing your card details"});
    });
  }

  handleChange = (event) => {
    const target = event.target;
    const value = target.type === 'checkbox' ? target.checked : target.value;
    const name = target.name;

    this.setState({
      [name]: value
    });
  }

  // Validation error handling
  onChange = (event) => {
    const errors = this.state.errors;
    let errorMessage = '';

    if(event.error) {
      // If error is present, display the error
      errors[event.field] = event.error
      errorMessage = event.error.message
    } else {
      errors[event.field] = null
      // If there's no error, check for existing error
      const _errors = Object.values(errors).filter(val => val)
      
      // The errorObject holds a message and code
      // Custom error messages can be displayed based on the error code
      const errorObj = _errors.pop();

      // Display existing message
      if(errorObj) errorMessage = errorObj.message
      else errorMessage = ''
    }
    this.setState({
      errors,
      errorMessage,
    })
  }

  render() {
    const { firstName, loading, errorMessage, token } = this.state;
    const { style, classes, locale, fonts } = this.state.options;
    return (
      <div className="ex3 container">
        <div className="ex3-wrap">      
          <form id="payment">
            <div className="ex3-contain">
              <div className="ex3-fieldset">
                <div className="ex3-field">                  
                    <input name="firstName" className={ firstName ? "ex3-input val" : "ex3-input"} type="text" placeholder="John Doe" value={firstName} onChange={this.handleChange} />
                    <i className="ex3-bar"></i>                  
                </div>
                {/* Pass all options as props to card component */}
                {/* Assign ref to call internal methods */}
                <CardComponent ref={this.cardRef} 
                  styles={style} 
                  classes={classes} 
                  className="fieldset field"
                  locale={locale}
                  fonts={fonts}
                  onChange={this.onChange}
                >       
                  {/* ^ Attach ready, change listeners to card component */}       

                  <div className="ex3-field">   
                    {/* Card number field */}
                    <CardNumber className="ex3-input" />
                    <i className="ex3-bar"></i>                  
                  </div>
                  <div className="ex3-fields">
                    <div className="ex3-field">                    
                        {/* Card expiry field */}
                        <CardExpiry className="ex3-input" />
                        <i className="ex3-bar"></i>                    
                    </div>
                    <div className="ex3-field">                    
                        {/* Card cvv field */}
                        <CardCVV className="ex3-input" />
                        <i className="ex3-bar"></i>                 
                    </div>
                  </div>
                </CardComponent>
              </div>
            </div>
            <button className={ loading ? "submit ex3-button" : "ex3-button"} onClick={this.authorize}>Authorize with 3DS</button>
            {errorMessage && <div className="error" role="alert">{errorMessage}</div>}
            {token && <div className="token" >{token}</div>}
          </form>
        </div>
      </div>
    );
  }
}

// components/angular-app/src/app/example4/example4.component.ts
import { Component, ChangeDetectorRef, OnInit } from '@angular/core';
import { PaymentIntent, AdditionalData } from '@chargebee/chargebee-js-angular-wrapper/lib/types';

@Component({
  selector: 'app-example4',
  templateUrl: './example4.component.html',
  styleUrls: ['./example4.component.scss']
})
export class Example4Component implements OnInit {
  firstName: string;
  loading: boolean;
  token: string;
  intent: PaymentIntent;
  additionalData: AdditionalData;
  cardComponent: any;

  // To store validation errors
  errorMessage: string;
  errors: any = {};

  // Using change detector to update validation errors on change
  changeDetector: ChangeDetectorRef;

  locale = 'en';
  styles = {
    base: {
      color: '#2a2d5b',
      fontWeight: '500',
      fontFamily: 'Raleway,-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica Neue, sans-serif',
      fontSize: '16px',
      fontSmoothing: 'antialiased',

      ':focus': {
        // color: '#424770',
      },

      '::placeholder': {
        color: '#9293AB',
        fontSize: '14px',
      },

      ':focus::placeholder': {
        color: '#666',
      },
    },
    invalid: {
      color: '#e41029',

      ':focus': {
        color: '#e44d5f',
      },
      '::placeholder': {
        color: '#FFCCA5',
      },
    },
  };

  fonts = [
    'https://fonts.googleapis.com/css?family=Raleway:300,500,600'
  ];

  classes = {
    focus: 'focus',
    invalid: 'invalid',
    empty: 'empty',
    complete: 'complete',
  };

  // Dependency injection of Change detector
  constructor(changeDetector: ChangeDetectorRef) {
    this.changeDetector = changeDetector;
  }

  ngOnInit() {
    this.createPaymentIntent();
  }

  createPaymentIntent(payload: any = {}) {
    return fetch('http://localhost:4000/payment_intent', {
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json'
      },
      method: 'POST',
      body: JSON.stringify(payload)
    }).then(response => response.json())
    .then(intent => {
      this.intent = intent;
      return intent;
    });
  }

  authorize() {
    this.loading = true;
    // Call tokenize method using card component instance
    this.cardComponent.authorizeWith3ds(this.intent, this.additionalData).then((authorizedIntent) => {
      this.intent = authorizedIntent;
      this.token = authorizedIntent.id;
      this.loading = false;
      this.errorMessage = '';
    }).catch((error) => {
      this.loading = false;
      this.errorMessage = 'Problem while tokenizing your card details';
      this.token = '';
    });
  }

  onChange(event) {
    // Validation Error handling
    if (event.error) {
      this.errors[event.field] = event.error;
      this.errorMessage = event.error.message;
    } else {
      this.errors[event.field] = null;
      // If there's no error, check for existing error
      const errors: Array<any> = Object.values(this.errors).filter(val => val);

      // The errorObject holds a message and code
      // Custom error messages can be displayed based on the error code
      const errorObj: any = errors.pop();

      // Display existing message
      if (errorObj) {
        this.errorMessage = errorObj.message;
      } else {
        this.errorMessage = '';
      }
    }
    this.changeDetector.detectChanges();
  }

  // Triggered on card component ready
  setComponent(component) {
    this.cardComponent = component;
  }

}

<div class="ex3 container">
  <div class="ex1-wrap">
    <form id="payment">
        <div class="ex1-contain">
          <div class="ex1-fieldset">
              <div class="ex1-field">                  
                  <input class="ex1-input" type="text" placeholder="John Doe" >  
                  <i class="ex1-bar"></i>                  
              </div> 
              
              <!-- To render Card field, use cbCardField directive -->
              <div id="card-field" cbCardField class="fieldset field" 
                [styles]="styles" 
                [classes]="classes" 
                [fonts]="fonts"
                [locale]="locale"
                (ready)="setComponent($event)"
                (change)="onChange($event)"
              >
                <div class="ex1-field">                  
                  <!-- Number field: use cbNumberField directive -->
                  <div id="number-field" cbNumberField class="ex1-input"></div>
                  <i class="ex1-bar"></i>                  
                </div>
                <div class="ex1-fields">
                  <div class="ex1-field"> 
                    <!-- Expiry field: use cbExpiryField directive -->                   
                    <div id="expiry-field" cbExpiryField class="ex1-input"></div>
                    <i class="ex1-bar"></i>                    
                  </div>
                  <div class="ex1-field">       
                    <!-- CVV field: use cbCvvField directive -->             
                    <div id="cvv-field" cbCvvField class="ex1-input"></div>
                    <i class="ex1-bar"></i>                 
                  </div>
                </div>
              </div>

          </div>
        </div>
        <button type="submit" [ngClass]="loading ? 'submit': ''" class="ex1-button" (click)="authorize()">3DS Authorize</button>
        <div class="error" role="alert" *ngIf="errorMessage">{{errorMessage}}</div>
        <div class="token" *ngIf="token">{{token}}</div>
    </form>
  </div>
</div>
