// api/front-end/angular/src/checkout_new/checkout_new.component.ts
import { Component } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { ChangeDetectorRef } from '@angular/core';


@Component({
  selector: 'checkout-new',
  templateUrl: './checkout_new.component.html',
  styleUrls: ['./checkout_new.component.css']
})
export class CheckoutNewComponent {
  first_name: string;
  last_name: string;
  email: string;
  company: string;
  phone: string;
  cbInstance: any;
  loading: boolean;
  errMsg: boolean;

  constructor(private http: HttpClient, private ref: ChangeDetectorRef) {
  }

  getFormUrlEncoded(toConvert) {
		const formBody = [];
		for (const property in toConvert) {
      const encodedKey = encodeURIComponent(property);
      if(toConvert[property]) {
        const encodedValue = encodeURIComponent(toConvert[property]);
        formBody.push(encodedKey + '=' + encodedValue);
      }
		}
		return formBody.join('&');
	}

  ngOnInit() {
    this.cbInstance = window['Chargebee'].init({
      site: "honeycomics-v3-test"
    });
  }

  openCheckout() {
    this.cbInstance.openCheckout({
      hostedPage: () => {
        this.loading = true;
        // Hit your end point that returns hosted page object as response
        // This sample end point will call the below api
        // You can pass hosted page object created as a result of checkout_new, checkout_existing, manage_payment_sources
        // https://apidocs.chargebee.com/docs/api/hosted_pages#checkout_new_subscription
        // https://apidocs.chargebee.com/docs/api/hosted_pages#checkout_existing_subscription
        // https://apidocs.chargebee.com/docs/api/hosted_pages#manage_payment_sources
        // If you want to use paypal, go cardless and plaid, pass embed parameter as false
        let data = {
          plan_id: "cbdemo_scale",
          first_name: this.first_name,
          last_name: this.last_name,
          email: this.email,
          phone: this.phone,
          company: this.company
        }
        return this.http.post("http://localhost:8000/api/generate_checkout_new_url", this.getFormUrlEncoded(data), {headers: new HttpHeaders({'Content-Type': 'application/x-www-form-urlencoded'})}).toPromise();
      },
      loaded: () => {
        console.log("checkout opened");
      },
      error: () => {
        this.loading = false;
        this.ref.markForCheck();
        this.errMsg = true;
      },
      close: () => {;
        this.loading = false;
        this.ref.detectChanges();
        console.log("checkout closed");
      },
      success: (hostedPageId) => {
        console.log(hostedPageId);
        // Hosted page id will be unique token for the checkout that happened
        // You can pass this hosted page id to your backend 
        // and then call our retrieve hosted page api to get subscription details
        // https://apidocs.chargebee.com/docs/api/hosted_pages#retrieve_a_hosted_page
      },
      step: (value) => {
          // value -> which step in checkout
          console.log(value);
      }
    });
  }
}
<div id="container" class="checkout container">
    <div id="customer-info" class="row">                
        <div class="col-sm-7" id="checkout_info">   
            <div id="subscribe-form">
                <div class="page-header">
                    <h3>Tell us about yourself</h3>
                </div>
                <div class="row">
                    <div class="col-sm-6"> 
                        <div class="form-group">
                            <label for="first_name">First Name</label>
                            <input type="text" class="form-control" [(ngModel)]="first_name">
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="last_name">Last Name</label>
                            <input type="text" class="form-control" [(ngModel)]="last_name">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="email]">Email</label>
                            <input type="text" class="form-control" [(ngModel)]="email">
                        </div>
                    </div> 
                                                
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="phone">Phone</label>
                            <input type="text" class="form-control" [(ngModel)]="phone">
                        </div>
                    </div>                   
                </div> 
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="company">Company</label>
                            <input type="text" class="form-control" [(ngModel)]="company">
                        </div>
                    </div>
                </div>                        
                <hr>                            
                <p class="text-danger" *ngIf="errorMsg">There were errors while submitting</p>
                <div class="form-inline">
                    <div class="form-group">
                      <input type="submit" (click)="openCheckout()" class="submit-btn btn btn-success btn-lg" value="Proceed to Payment">
                    </div>
                    <div class="form-group">
                      <span ref="loader" class="subscribe-process process" *ngIf="loading">Processing&hellip;</span>
                    </div>
                </div>                        
              </div>
        </div>
        <div class="col-sm-4 cb-order-list col-sm-offset-1">
            <div class="page-header">
                <h3>Subscription Details</h3>
            </div>
            <div class="media">                    	
                <img src="/assets/images/plan.png" alt="chargebee demo" class="pull-left">
                <div class="media-body">
                  <p class="h4">Marvel Classics</p>
                    <p class="h4">$9 <small><em>per month</em></small></p>
                </div>
            </div>
        </div>
    </div>
    <div id="checkout-info" class="row">

    </div>
</div>

// api/front-end/react-app/src/CheckoutNew.js
import React, { Component } from 'react';

import './App.css';
import axios from 'axios'

axios.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded';

const urlEncode = function(data) {
  var str = [];
  for (var p in data) {
      if (data.hasOwnProperty(p) && (!(data[p] == undefined || data[p] == null))) {
          str.push(encodeURIComponent(p) + "=" + (data[p] ? encodeURIComponent(data[p]) : ""));
      }
  }
  return str.join("&");
}

class CheckoutNew extends Component {
  constructor(props) {
    super(props);
    this.state = {
      cbInstance: window.Chargebee.init({
        site: "honeycomics-v3-test"
      }),
      first_name: "",
      last_name: "",
      company: "",
      email: "",
      phone: "",
      loading: "",
      errorMsg: ""
    };
    this.handleCheckout = this.handleCheckout.bind(this);
    this.handleChange = this.handleChange.bind(this);
  }

  handleCheckout(event) {
    this.setState({loading: true});
    this.state.cbInstance.openCheckout({
      hostedPage: () => {
        var data = {
          first_name: this.state.first_name,
          last_name: this.state.last_name,
          email: this.state.email,
          phone: this.state.phone,
          company: this.state.company,
          plan_id: "cbdemo_scale"
        };
        return axios.post("http://localhost:8000/api/generate_checkout_new_url", urlEncode(data)).then((response) => response.data)
      },
      success(hostedPageId) {
        console.log(hostedPageId);
      },
      close:() => {
        this.setState({loading: false});
        console.log("checkout new closed");
      },
      step(step) {
        console.log("checkout", step);
      }
    });
    event.preventDefault();
  }

  handleChange(event) {
    const target = event.target;
    const value = target.type === 'checkbox' ? target.checked : target.value;
    const name = target.name;

    this.setState({
      [name]: value
    });
  }

  render() {
    return (
      <div id="container" className="checkout container">
        <div id="customer-info" className="row">                
          <div className="col-sm-7" id="checkout_info">   
              <form id="subscribe-form" onSubmit={this.handleCheckout}>
                  <div className="page-header">
                      <h3>Tell us about yourself</h3>
                  </div>
                  <div className="row">
                      <div className="col-sm-6"> 
                          <div className="form-group">
                              <label htmlFor="first_name">First Name</label>
                              <input type="text" name="first_name" className="form-control" value={this.state.first_name} onChange={this.handleChange}/>
                          </div>
                      </div>
                      <div className="col-sm-6">
                          <div className="form-group">
                              <label htmlFor="last_name">Last Name</label>
                              <input type="text" name="last_name" className="form-control" value={this.state.last_name} onChange={this.handleChange}/>
                          </div>
                      </div>
                  </div>
                  <div className="row">
                      <div className="col-sm-6">
                          <div className="form-group">
                              <label htmlFor="email]">Email</label>
                              <input type="text" name="email" className="form-control" value={this.state.email} onChange={this.handleChange}/>
                          </div>
                      </div> 
                                                  
                      <div className="col-sm-6">
                          <div className="form-group">
                              <label htmlFor="phone">Phone</label>
                              <input type="text" name="phone" className="form-control" value={this.state.phone} onChange={this.handleChange}/>
                          </div>
                      </div>                   
                  </div> 
                  <div className="row">
                      <div className="col-sm-6">
                          <div className="form-group">
                              <label htmlFor="company">Company</label>
                              <input type="text" name="company"  className="form-control" value={this.state.company} onChange={this.handleChange}/>
                          </div>
                      </div>
                  </div>                        
                  <hr/>                            
                  {this.state.errorMsg && <p className="text-danger">There were errors while submitting</p>}
                  <div className="form-inline">
                      <div className="form-group">
                        <input type="submit" className="submit-btn btn btn-success btn-lg" value="Proceed to Payment"/>
                      </div>
                      <div className="form-group">
                        {this.state.loading && <span ref="loader" className="subscribe-process process" >Processing&hellip;</span>}
                      </div>
                  </div>                        
                </form>
          </div>
          <div className="col-sm-4 cb-order-list col-sm-offset-1">
              <div className="page-header">
                  <h3>Subscription Details</h3>
              </div>
              <div className="media">                    	
                  <img src="/assets/images/plan.png" alt="chargebee demo" className="pull-left" />
                  <div className="media-body">
                    <p className="h4">Marvel classics</p>
                      <p className="h4">$9 <small><em>per month</em></small></p>
                  </div>
              </div>
          </div>
        </div>
      </div>
    );
  }
}

export default CheckoutNew;
