// api/front-end/react-app/src/CheckoutExistingLogin.js
import React, { Component } from 'react';
import { withRouter } from 'react-router-dom'


export default class CheckoutExistingLogin extends Component {
  constructor(props) {
    super(props);
  }
  render() {
    const Button = withRouter(({ history }) => (
      <div className="form-group">
        <div className="col-sm-8 col-sm-offset-4">
          <button
            type='button'
            onClick={() => { history.push('/checkout-existing/profile') }}
            className="btn btn-success"
          >
            Login
          </button>
        </div>
      </div>
    ))
    
    return (
      <div className="container">
        <div className=" col-sm-6 col-sm-offset-3">
          <div className="panel panel-success">
            <div className="panel-heading">Login</div>
            <div className="panel-body">
              <div className="form-horizontal">
                <div className="form-group">
                  <label className="col-sm-4 control-label">User Name</label>
                  <div className="col-sm-8">
                    <input type="text" className="form-control" placeholder="Enter User Name" value='kim' />
                    <small className="text-danger"></small>
                  </div>
                </div>
                <div className="form-group">
                  <label className="col-sm-4 control-label">Password</label>
                  <div className="col-sm-8">
                    <input type="password" className="form-control" placeholder="Enter Password" value="thisismypassword" />
                    <small className="text-danger"></small>
                  </div>
                </div>
                <div className="form-group">                    
                  <div className="col-sm-8 col-sm-offset-4">
                    <Button/>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    )
  }
}

// api/front-end/angular/src/checkout_existing/login/checkout_existing_login.component.ts
import { Component } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Router } from '@angular/router';


@Component({
  selector: 'checkout-existing-login',
  templateUrl: './checkout_existing_login.component.html',
  styleUrls: ['./checkout_existing_login.component.css']
})
export class CheckoutExistingLoginComponent {
  constructor(private router: Router) {
  
  }

  login() {
    this.router.navigateByUrl("/checkout_existing/profile");
  }
}
<div class="container">
  <div class=" col-sm-6 col-sm-offset-3">
    <div class="panel panel-success">
      <div class="panel-heading">Login</div>
      <div class="panel-body">
        <div class="form-horizontal">
          <div class="form-group">
            <label class="col-sm-4 control-label">User Name</label>
            <div class="col-sm-8">
              <input type="text" class="form-control" placeholder="Enter User Name" value='kim'>
              <small class="text-danger"></small>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-4 control-label">Password</label>
            <div class="col-sm-8">
              <input type="password" class="form-control" placeholder="Enter Password" value="thisismypassword">
              <small class="text-danger"></small>
            </div>
          </div>
          <div class="form-group">                    
            <div class="col-sm-8 col-sm-offset-4">
              <input type="submit" class="btn btn-success" (click)="login()" value="Login">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
